name: "Generate Squall People"
description: "Generate the data for the Squall People page"
author: "Stanislav Dubrovskyi <s.dubrovskyi@cleverdec.com>"
inputs:
  token:
    description: 'User token, to read the GitHub API. Can be passed in using {{ secrets.ACTION_TOKEN }}'
    required: true
  standard_token:
    description: 'Default GitHub Action token, used for the PR. Can be passed in using {{ secrets.GITHUB_TOKEN }}'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
